[package]
name = "points-api-importer"
version = "0.1.0"
authors = ["duxet <duxetlg@gmail.com>"]

[dependencies]
clap = "2.26"
osmpbfreader = "0.11"
postgis = "0.5"
postgres = "0.15"
postgres-derive = "0.3"
